# Generated by Django 4.2.6 on 2023-12-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_slug_blog_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='raw_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.CharField(default='', max_length=190),
            preserve_default=False,
        ),
    ]
