# Generated by Django 4.0 on 2023-12-22 22:14

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=blogs.models.upload_image_to),
        ),
    ]
